version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1.9-node
    working_directory: ~/repo
    steps:
      - run: sudo apt-get install -y libpng-dev
      - run:
          name: Install PHP Extensions
          command: sudo docker-php-ext-install gd
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}  

  test:
    docker:
      - image: circleci/php:7.1.9-node
    working_directory: ~/repo
    steps:
      - run: sudo apt-get install -y libpng-dev
      - run:
          name: Install PHP Extensions
          command: sudo docker-php-ext-install gd
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run: cp .env.testing .env
      - run: 
          name: PHPUnit
          command: ./vendor/bin/phpunit 
